# Eval config for Phi-4-reasoning-plus (14B params).
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi evaluate -c oumi://configs/recipes/phi4/evaluation/reasoning_plus_eval.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/evaluate/evaluate.html
#   - Config class: oumi.core.configs.EvaluationConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/evaluation_config.py
#   - Other eval configs: configs/**/evaluation/

model:
  model_name: "microsoft/Phi-4-reasoning-plus"
  model_max_length: 32768
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True
  shard_for_eval: True

generation:
  batch_size: 4

tasks:
  # For all available tasks, see https://oumi.ai/docs/en/latest/user_guides/evaluate/evaluate.html
  - evaluation_backend: lm_harness
    task_name: mmlu_college_computer_science
    eval_kwargs:
      num_fewshot: 5

enable_wandb: True
