# Job config to GRPO tune "Qwen2-0.5B-Instruct" with DDP on GCP.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi launch up -c configs/examples/grpo_tldr/gcp_job.yaml --cluster tiny-qwen-grpo
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml

name: tiny-qwen-grpo

resources:
  cloud: gcp
  accelerators: "A100:4"
  use_spot: false

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: tiny-qwen.grpo

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu]

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  export PER_DEVICE_BATCH_SIZE=3
  export GLOBAL_BATCH_SIZE=$((${OUMI_TOTAL_NUM_GPUS} * ${PER_DEVICE_BATCH_SIZE}))
  export GRPO_NUM_GENERATIONS=6

  if (test "$(( ${GLOBAL_BATCH_SIZE} % ${GRPO_NUM_GENERATIONS} ))" -ne 0); then
    echo "Global batch size (${GLOBAL_BATCH_SIZE}) must be divisible by num_generations (${GRPO_NUM_GENERATIONS})"
    exit 1
  fi

  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c configs/examples/grpo_tldr/train.yaml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
      --training.per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
      --training.grpo.num_generations ${GRPO_NUM_GENERATIONS} \
      --training.max_steps 20 \
      --training.save_steps 0 \
      --training.save_final_model true

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
