# Llava 7B full fine-tune training config.
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi train -c configs/recipes/vision/llava_7b/sft/train.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/*train.yaml

model:
  model_name: "llava-hf/llava-1.5-7b-hf"
  torch_dtype_str: "bfloat16"
  model_max_length: 1024
  trust_remote_code: True
  attn_implementation: "sdpa"
  chat_template: "llava"
  freeze_layers:
    - "vision_tower"

data:
  train:
    collator_name: "vision_language_with_padding"
    use_torchdata: True
    datasets:
      - dataset_name: "merve/vqav2-small"
        split: "validation"
        shuffle: True
        seed: 42
        transform_num_workers: "auto"
        dataset_kwargs:
          processor_name: "llava-hf/llava-1.5-7b-hf"
          # limit: 8192 # Uncomment to limit dataset size!
          return_tensors: True

      # Below are examples of other vision SFT datasets
      # - dataset_name: "HuggingFaceH4/llava-instruct-mix-vsft"
      #   split: "train"
      #   shuffle: True
      #   seed: 42
      #   transform_num_workers: "auto"
      #   dataset_kwargs:
      #     processor_name: "llava-hf/llava-1.5-7b-hf"
      #     limit: 8192
      #     return_tensors: True
      # - dataset_name: "coco_captions"
      #   split: "train"
      #   trust_remote_code: True
      #   dataset_kwargs:
      #     processor_name: "llava-hf/llava-1.5-7b-hf"
      #     limit: 8192
      #     return_tensors: True
      # - dataset_name: vision_language_jsonl
      #   dataset_path: "training.jsonl"  # See notebook for example how to generate this file
      #   dataset_kwargs:
      #     data_column: "messages"
      #     processor_name: "llava-hf/llava-1.5-7b-hf"

training:
  output_dir: "output/vlm_finetuned"
  trainer_type: "TRL_SFT"
  enable_gradient_checkpointing: True
  per_device_train_batch_size: 6
  gradient_accumulation_steps: 8
  max_steps: 20

  gradient_checkpointing_kwargs:
    # Reentrant docs: https://pytorch.org/docs/stable/checkpoint.html#torch.utils.checkpoint.checkpoint
    use_reentrant: False
  ddp_find_unused_parameters: False
  empty_device_cache_steps: 2
  compile: False

  optimizer: "adamw_torch_fused"
  learning_rate: 2e-5
  warmup_ratio: 0.03
  weight_decay: 0.0
  lr_scheduler_type: "cosine"

  logging_steps: 5
  save_steps: 0
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32
  include_performance_metrics: True
  log_model_summary: False
  enable_wandb: True
