# vLLM Inference config for Llama-4-Scout-17B-16E-Instruct GGUF.
#
# Requirements:
#   - Run `pip install oumi[gpu]`
#
# Usage:
#   oumi infer -i -c configs/recipes/llama4/inference/scout_instruct_gguf_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF"
  tokenizer_name: "meta-llama/Llama-4-Scout-17B-16E-Instruct"
  model_max_length: 8192
  torch_dtype_str: "float16"
  trust_remote_code: True
  attn_implementation: "sdpa"
  model_kwargs:
    filename: "Llama-4-Scout-17B-16E-Instruct-UD-Q4_K_M.gguf"

generation:
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 0.9

engine: VLLM
