# Inference config for Llama 4 Scout-17B-16E Instruct with a NATIVE engine.
#
# Requirements:
#   - Set the `TOGETHER_API_KEY` env var to your Together API key.
#
# Usage:
#   oumi infer -i -c configs/recipes/llama4/inference/scout_instruct_together_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "meta-llama/Llama-4-Scout-17B-16E-Instruct"

generation:
  max_new_tokens: 2048

engine: TOGETHER
