# Phi3 vision vLLM inference config.
#
# Requirements:
#   - Run `pip install oumi[gpu]`
#
# Usage:
#   oumi infer -i -c configs/recipes/vision/phi3/inference/vllm_infer.yaml \
#     --image "tests/testdata/images/the_great_wave_off_kanagawa.jpg"
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "microsoft/Phi-3-vision-128k-instruct"
  torch_dtype_str: "bfloat16"
  model_max_length: 4096
  chat_template: "phi3-instruct"
  trust_remote_code: True

generation:
  max_new_tokens: 64

engine: VLLM
