# LlamaCPP Inference config for Qwen3-4B-Instruct GGUF (macOS compatible).
#
# Requirements:
#   - Run `pip install oumi[llama_cpp]`
#
# Usage:
#   # 1. Download the GGUF file to current working directory:
#   hf download unsloth/Qwen3-4B-Instruct-2507-GGUF \
#     Qwen3-4B-Instruct-2507-UD-Q5_K_XL.gguf --local-dir .
#
#   # 2. Run inference:
#   oumi infer -i -c configs/recipes/qwen3/inference/4b_instruct_gguf_macos_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "unsloth/Qwen3-4B-Instruct-2507-GGUF"
  tokenizer_name: "Qwen/Qwen3-4B-Instruct-2507"
  model_max_length: 16384
  torch_dtype_str: "float16"
  trust_remote_code: True
  model_kwargs:
    filename: "Qwen3-4B-Instruct-2507-UD-Q5_K_XL.gguf"

generation:
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 0.9

engine: LLAMACPP
