# Job config to full fine-tune InternVL 3.0 1B on GCP on a single GPU.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `hf auth login`
#
# Usage:
#   oumi launch up --config configs/recipes/vision/internvl3/sft/full/gcp_job.yaml --cluster internvl3
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml

name: internvl3-sft-oumi-train

resources:
  cloud: gcp
  accelerators: "A100:1" # Model has been tested with a single GPU only.
  use_spot: false
  disk_size: 1000 # Disk size in GBs

num_nodes: 1 # Set it to N for multi-node training.

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials
  ~/.cache/huggingface/token: ~/.cache/huggingface/token # HF credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: internvl3.fft.oumi

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu] hf_transfer

  # Extra requirements for this model:
  pip install timm

  # Install model from HF Hub. This tool increases download speed compared to
  # downloading the model during training.
  HF_HUB_ENABLE_HF_TRANSFER=1 hf download OpenGVLab/InternVL3-1B-hf

  # Use transformers latest version (4.52.0.dev0)
  # Use this with caution, as it might break some of Oumi's features which is as of
  # today (April 23rd 2025) is using transformers <4.52.
  pip install git+https://github.com/huggingface/transformers.git

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  if test ${OUMI_TOTAL_NUM_GPUS} -gt 1; then
    RUN_COMMAND="oumi distributed torchrun -m oumi train"
  else
    RUN_COMMAND="oumi train"
  fi

  set -x
  ${RUN_COMMAND}\
    -c configs/recipes/vision/internvl3/sft/full/train.yaml \
    --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
    --training.max_steps 20 \
    --training.save_steps 0 \
    --training.save_final_model false

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
