# Llama 3.2 (1B) DPO train config.
#
# Usage:
#   oumi train -c configs/recipes/llama3_2/dpo/1b_qlora_dpo.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/evaluation/, configs/**/inference/, configs/**/sft/

model:
  model_name: "meta-llama/Llama-3.2-1B-Instruct"
  model_max_length: 131072
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "mlabonne/orpo-dpo-mix-40k"

training:
  optimizer: "adamw_torch"
  use_peft: true
  output_dir: "output/llama3_2_1b.dpo"
  trainer_type: "TRL_DPO"
  per_device_train_batch_size: 2

peft:
  q_lora: True
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_quant_storage: "bfloat16"
  bnb_4bit_compute_dtype: "bfloat16"
  lora_r: 16
  lora_alpha: 32
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
