# Inference config for Phi-4-reasoning-plus (14B params).
#
# Usage:
#   oumi infer -i -c oumi://configs/recipes/phi4/inference/reasoning_plus_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "microsoft/Phi-4-reasoning-plus"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True

generation:
  max_new_tokens: 2048

engine: NATIVE
