# Job config to HSDP (FSDP HYBRID_SHARD) pre-training of Llama 3.1 8B on 1 GCP node.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `hf auth login`
#   - Request access to Llama 3.1: https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct
#
# Usage:
#   oumi launch up -c configs/recipes/llama3_1/pretraining/8b/gcp_job.yaml --cluster llama8b-pretrain-hsdp
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml

name: llama3.1_8B_hsdp

num_nodes: 1
resources:
  cloud: gcp
  accelerators: "A100:4"
  use_spot: false
  disk_size: 500 # in GB -> we can save the final model locally.

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials
  ~/.cache/huggingface/token: ~/.cache/huggingface/token # HF credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llama3.1_8B_hsdp

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu] hf_transfer
  # Install model from HF Hub. This tool increases download speed compared to
  # downloading the model during training.
  HF_HUB_ENABLE_HF_TRANSFER=1 hf download meta-llama/Llama-3.1-8B --exclude original/*

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c configs/recipes/llama3_1/pretraining/8b/train.yaml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
      --training.max_steps 20 \
      --training.save_steps 0 \
      --training.save_final_model false

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
