name: Bug Report
description: File a bug report to help us improve Oumi
title: "[Bug]"
labels: ["bug", "triage"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Give a detailed description of the bug you encountered.
      placeholder: Detailed description of the bug...
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        Please provide a code snippet that allows us to quickly reproduce the bug.
        Include any error messages, logs, and stack traces if available.

      placeholder: |
        Steps to reproduce:

          1.
          2.
          3.

    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system information by running `oumi env` and pasting its output below.
      placeholder: |
        Please paste the output of `oumi env` here. If you can't run this command, please provide:
        - Operating system
        - Python version
        - Oumi version
        - PyTorch version
        - Any other relevant system information
      render: shell
    validations:
      required: true
