# Falcon-E DPO train config.
#
# Usage:
#   oumi train -c configs/recipes/falcon_e/dpo/falcon_e_1b_instruct/dpo.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/*train.yaml

model:
  model_name: "tiiuae/Falcon-E-1B-Instruct"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True
  enable_liger_kernel: False
  tokenizer_kwargs:
    pad_token: "<|pad|>"
  model_revision: "prequantized"

data:
  train:
    datasets:
      - dataset_name: "mlabonne/orpo-dpo-mix-40k"

training:
  optimizer: "adamw_torch"
  use_peft: false
  output_dir: "output/falcon-e-1b.dpo"
  trainer_type: "TRL_DPO"
  per_device_train_batch_size: 2
