# Phi3 LoRA train config for macOS.
#
# Usage:
#   oumi train -c configs/recipes/phi3/sft/lora_macos_train.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/*train.yaml

model:
  model_name: "microsoft/Phi-3-mini-4k-instruct"
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "yahma/alpaca-cleaned"
    target_col: "prompt"

training:
  optimizer: "adamw_torch"
  use_peft: true
  trainer_type: "TRL_SFT"
  output_dir: "output/phi3.lora"

peft:
  q_lora: False
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
