# verl GRPO training config for Countdown.
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi train -c configs/examples/grpo_verl_countdown/train.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/*train.yaml

model:
  model_name: "d1shs0ap/cognitive-behaviors-Llama-3.2-3B"

data:
  train:
    datasets:
      - dataset_name: "d1shs0ap/countdown"
        split: "train"
  validation:
    datasets:
      - dataset_name: "d1shs0ap/countdown"
        split: "test"

training:
  trainer_type: "VERL_GRPO"
  num_train_epochs: 1
  save_steps: -1
  eval_strategy: "steps"
  eval_steps: 50

  learning_rate: 1.0e-6
  enable_gradient_checkpointing: True

  reward_functions: ["countdown"]

  grpo:
    max_completion_length: 1024
    use_vllm: True
    temperature: 1.0
    vllm_gpu_memory_utilization: 0.4

  verl_config_overrides:
    data:
      train_batch_size: 64
      val_batch_size: 640
      max_prompt_length: 256
    actor_rollout_ref:
      model:
        use_remove_padding: True
      actor:
        use_kl_loss: True
        kl_loss_coef: 0.001
        kl_loss_type: "low_var_kl"
        ppo_mini_batch_size: 16
        ppo_micro_batch_size_per_gpu: 2
      rollout:
        log_prob_micro_batch_size_per_gpu: 2
        tensor_model_parallel_size: 2
        n: 16
      ref:
        log_prob_micro_batch_size_per_gpu: 1
        fsdp_config:
          param_offload: True
    algorithm:
      kl_ctrl:
        kl_coef: 0.001
    trainer:
      critic_warmup: 0
      val_before_train: False
      n_gpus_per_node: 2
      nnodes: 1

  output_dir: "output/grpo_verl_countdown"
  run_name: "grpo_verl_countdown"
  enable_wandb: True
