# LlamaCPP Inference config for Llama-3.3-Nemotron-Super-49B GGUF (macOS compatible).
#
# Requirements:
#   - Run `pip install oumi[llama_cpp]`
#
# Usage:
#   # 1. Download the GGUF file to current working directory:
#   hf download bartowski/nvidia_Llama-3_3-Nemotron-Super-49B-v1-GGUF \
#     nvidia_Llama-3_3-Nemotron-Super-49B-v1-Q4_K_M.gguf --local-dir .
#
#   # 2. Run inference:
#   oumi infer -i -c configs/recipes/llama3_3/inference/nemotron_super_49b_gguf_macos_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "bartowski/nvidia_Llama-3_3-Nemotron-Super-49B-v1-GGUF"
  tokenizer_name: "nvidia/Llama-3.3-Nemotron-Super-49B-v1"
  model_max_length: 8192
  torch_dtype_str: "float16"
  trust_remote_code: True
  model_kwargs:
    filename: "nvidia_Llama-3_3-Nemotron-Super-49B-v1-Q4_K_M.gguf"

generation:
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 0.9

engine: LLAMACPP
