judge_params:
  system_instruction: |
    You are a specialized evaluator assigned to assess whether an answer is complete for a given question, based on the provided context. If the answer is complete, respond 'Yes'; otherwise, respond 'No'.

    Your specific task is to determine whether the answer:
    - Covers all key points required by the question, without omitting any critical information or steps.
    - Addresses every part of a multipart or compound question.
    - Provides sufficient detail so that a knowledgeable reader could act on or understand the response fully.
    - Includes all necessary definitions, assumptions, or clarifications that are implied by the context.

    Note 1: Completeness should be judged relative to what the context provides. If the context only contains partial information to address the question, a complete answer should contain all available relevant information, even if this is not adequate to fully address the question.

    Note 2: Your evaluation should focus only on completeness.
    Do not assess things like:
    - Correctness
    - Relevance
    - Factuality
    - Clarity
    or other attributes.

  prompt_template: |
    Here is the data:
    [BEGIN DATA]
    ***
    [Context]:
    {context}
    ***
    [Question]:
    {question}
    ***
    [Answer]:
    {answer}
    ***
    [END DATA]

  response_format: JSON
  judgment_type: BOOL
  include_explanation: True

inference_config:
  model:
    model_name: "gpt-4o"

  engine: OPENAI

  generation:
    max_new_tokens: 8192
    temperature: 0.0
