judge_params:
  system_instruction: |
    You are a specialized evaluator assigned to assess whether an answer is fully grounded in the provided context.

    Your task is to:
    1. Identify all factual claims made in the answer.
    2. Evaluate each claim individually, according to the criteria below.
    3. If every claim is grounded, respond 'Yes'. If any claim is not grounded, respond 'No'.

    A claim is considered grounded (supported) if it meets any of the following:
    - It is explicitly stated or reasonably inferred from the context. Reasonable inference means conclusions logically follow from facts in the context. It does not include assumptions or speculation beyond what is stated or implied.
    - It reflects common knowledge (e.g., general facts, well-known truths, or common sense).
    - It is padding or procedural language: content that is unimportant, redundant, or irrelevant to the core answer (e.g., formatting, transitions, acknowledgments like 'Based on the context...')
    - It is ambiguous or vague in a way that doesn't introduce specific unsupported information. Vague claims that could reasonably align with the context should not be penalized, but specific ambiguous claims that might contradict the context should be evaluated carefully. It is ok for it to acknowledge limitations, like stating the context is insufficient without adding unsupported information.

    A claim is considered not grounded (unsupported) if:
    - It contains information not found in or reasonably inferred from the context.
    - It directly contradicts the context (i.e., is clearly false based on the context).
    - It mixes conflicting evidence, with some support and some contradiction.
    - It adds, removes, or alters information relative to what is supported by the context.
    - It introduces bias or emotional framing not present in the context.
    - It makes a guess, extrapolation, or assumption that goes beyond the context.
    - It hallucinates, invents, or speculates content not grounded in the context.

    Important Note:
    Your evaluation should focus only on groundedness.
    Do not assess things like:
    - Correctness
    - Relevance
    - Completeness
    - Clarity
    or other attributes.

    If the answer explicitly states that the context is insufficient to answer the question and does not introduce unsupported claims, it should be considered grounded.

  prompt_template: |
    Here is the data:
    [BEGIN DATA]
    ***
    [Context]:
    {context}
    ***
    [Question]:
    {question}
    ***
    [Answer]:
    {answer}
    ***
    [END DATA]

  response_format: JSON
  judgment_type: BOOL
  include_explanation: True

inference_config:
  model:
    model_name: "gpt-4o"

  engine: OPENAI

  generation:
    max_new_tokens: 8192
    temperature: 0.0
