# Zephyr QLora job config.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `hf auth login`
#   - Request access to Mistral: https://huggingface.co/mistralai/Mistral-7B-v0.1
#
# Usage:
#   oumi launch up -c src/experimental/configs/projects/zephyr/sft/qlora_gcp_job.yaml --cluster zephyr-7b-qlora
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml

name: zephyr-7b-qlora

resources:
  cloud: gcp
  accelerators: "A100:8"
  # If you don't have quota for a non-spot VM, try setting use_spot to true.
  # However, make sure you are saving your output to a mounted cloud storage in case of
  # preemption. For more information, see:
  # https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#mount-cloud-storage
  use_spot: false
  disk_size: 200 # Disk size in GB
  # region: us-west3  # Uncomment this line to only consider a specific region.

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials
  ~/.cache/huggingface/token: ~/.cache/huggingface/token # HF credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: zephyr.7b.qlora

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu]

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  oumi distributed torchrun \
    -m oumi train \
    -c src/experimental/configs/projects/zephyr/sft/qlora_train.yaml \
    --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
    --training.enable_wandb true \
    --training.enable_tensorboard true \
    --training.include_performance_metrics false

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
