# Llava 7B inference config.
#
# Usage:
#   oumi infer -i -c configs/recipes/vision/llava_7b/inference/infer.yaml \
#     --image "tests/testdata/images/the_great_wave_off_kanagawa.jpg"
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "llava-hf/llava-1.5-7b-hf"
  torch_dtype_str: "bfloat16"
  model_max_length: 1024
  chat_template: "llava"
  trust_remote_code: True

generation:
  max_new_tokens: 32
  batch_size: 1

engine: NATIVE
