# FFT config for QwQ (based on Qwen2.5 32B).
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi train -c configs/recipes/qwq/sft/full_train.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/*train.yaml

model:
  model_name: "Qwen/QwQ-32B"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "yahma/alpaca-cleaned" # 51,760 examples
    target_col: "prompt"

training:
  trainer_type: "TRL_SFT"
  save_steps: 200
  num_train_epochs: 3
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 1

  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  optimizer: "adamw_torch_fused"
  learning_rate: 2.0e-05
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.02

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 16

  logging_steps: 100
  empty_device_cache_steps: 50
  output_dir: "output/qwq.fft"
  include_performance_metrics: True
  enable_wandb: True

fsdp:
  enable_fsdp: True
  cpu_offload: True
  forward_prefetch: True
  sharding_strategy: "FULL_SHARD"
  state_dict_type: "SHARDED_STATE_DICT"
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "Qwen2DecoderLayer"
