# LlamaCPP Inference config for Gemma-3n-E4B-it GGUF (macOS compatible).
#
# Requirements:
#   - Run `pip install oumi[llama_cpp]`
#
# Usage:
#   # 1. Download the GGUF file to current working directory:
#   hf download unsloth/gemma-3n-E4B-it-GGUF \
#     gemma-3n-E4B-it-UD-Q5_K_XL.gguf --local-dir .
#
#   # 2. Run inference:
#   oumi infer -i -c configs/recipes/gemma3/inference/3n_e4b_it_gguf_macos_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "unsloth/gemma-3n-E4B-it-GGUF"
  tokenizer_name: "google/gemma-3n-E4B-it"
  model_max_length: 16384
  torch_dtype_str: "float16"
  trust_remote_code: True
  model_kwargs:
    filename: "gemma-3n-E4B-it-UD-Q5_K_XL.gguf"

generation:
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 0.9

engine: LLAMACPP
