# Memory-Optimized Full Fine-Tuning config for Qwen2.5-7B-Instruct
# Based on LIMO paper configuration: https://arxiv.org/abs/2502.03387
# Enhanced with DeepSpeed ZeRO-3 memory optimizations to prevent VRAM OOM
# YARN RoPE scaling for extended context length (131072 tokens)
#
# Memory Optimizations Applied:
# - Optimizer offloading to CPU (30-50% VRAM reduction, ~5-10% slower)
# - Reduced bucket sizes for communication efficiency
# - Aggressive ZeRO-3 parameter management settings
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `hf auth login`
#
# Usage:
#   oumi train -c configs/projects/limo/qwen2.5_7b_fft_yarn_deepspeed_memory_optimized_train.yaml

model:
  model_name: "Qwen/Qwen2.5-7B-Instruct"
  model_max_length: 131072 # Extended context length: 32768 * 4.0 = 131072
  torch_dtype_str: "bfloat16"
  # attn_implementation: "flash_attention_2"  # Match LIMO FA2
  load_pretrained_weights: True
  trust_remote_code: True
  enable_liger_kernel: True
  tokenizer_pad_token: "<|endoftext|>" # Set pad token to eos token for Qwen2.5
  model_kwargs:
    rope_scaling:
      type: "yarn"
      factor: 4.0 # Scales 32768 * 4.0 = 131072
      original_max_position_embeddings: 32768

data:
  train:
    datasets:
      - dataset_name: "PromptResponseDataset"
        split: "train"
        dataset_kwargs:
          hf_dataset_path: "GAIR/LIMO"
          prompt_column: "question"
          response_column: "solution"
        shuffle: True
        seed: 42

training:
  trainer_type: "TRL_SFT"
  # Full fine-tuning (no PEFT)
  save_steps: 0
  num_train_epochs: 5
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2

  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  optimizer: "adamw_torch_fused"
  learning_rate: 2e-5
  warmup_ratio: 0.05
  weight_decay: 0.03
  max_grad_norm: 1e-3
  lr_scheduler_type: "cosine"
  compile: False

  dataloader_num_workers: 64 # Match LIMO preprocessing workers
  dataloader_prefetch_factor: 32

  logging_steps: 50
  log_model_summary: False
  empty_device_cache_steps: 50
  output_dir: "output/qwen2.5_7b_limo_fft_yarn_memory_optimized"
  include_performance_metrics: True
  enable_wandb: True
  save_final_model: True

# DeepSpeed configuration optimized for memory efficiency
deepspeed:
  enable_deepspeed: True
  zero_stage: "ZERO_3"
  precision: "BF16"

  # ZeRO-3 communication optimization with reduced bucket sizes
  allgather_bucket_size: 50000000 # Reduced from auto/200M to 50M for memory efficiency
  overlap_comm: True
  reduce_bucket_size: 50000000 # Reduced from auto/200M to 50M
  contiguous_gradients: True

  # Aggressive ZeRO-3 memory management settings
  sub_group_size: 100000000 # Reduced from 1e9 to 1e8 for tighter memory control
  stage3_prefetch_bucket_size: 50000000 # Changed from "auto" to 50M for predictable memory usage
  stage3_param_persistence_threshold: 100000 # Changed from "auto" to 100K - keep fewer params in memory
  stage3_max_live_parameters: 100000000 # Reduced from 1e9 to 1e8 - more frequent parameter eviction
  stage3_max_reuse_distance: 100000000 # Reduced from 1e9 to 1e8 - tighter parameter reuse window
  stage3_gather_16bit_weights_on_model_save: False

  # Enable optimizer offloading (major VRAM savings with minimal runtime cost)
  offload_optimizer:
    device: "CPU"
    pin_memory: True
    buffer_count: 4

  # Memory optimization settings
  zero_allow_untested_optimizer: True
  zero_force_ds_cpu_optimizer: True # Use optimized CPU optimizer when offloading

  # Emergency option: Enable parameter offloading for extreme memory constraints
  # Uncomment these lines if still experiencing OOM (adds ~20-30% runtime overhead)
  # offload_param:
  #   device: "CPU"
  #   pin_memory: True
  #   buffer_count: 4

  # Logging
  steps_per_print: 10
  wall_clock_breakdown: False
