# Full Fine-Tuning config for Qwen2.5-7B-Instruct on tbench_traces_sharegptv1 dataset
# Based on LIMO paper configuration: https://arxiv.org/abs/2502.03387
# Modified to use ShareGPT format dataset from https://huggingface.co/datasets/mlfoundations-dev/tbench_traces_sharegptv1
# Enhanced with YARN RoPE scaling for extended context length (131072 tokens)
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `hf auth login`
#
# Usage:
#   oumi train -c configs/projects/limo/qwen2.5_7b_fft_yarn_deepspeed.yaml

model:
  model_name: "Qwen/Qwen2.5-7B-Instruct"
  model_max_length: 131072 # Extended context length: 32768 * 4.0 = 131072
  torch_dtype_str: "bfloat16"
  # attn_implementation: "flash_attention_2"  # Match LIMO FA2
  load_pretrained_weights: True
  trust_remote_code: True
  enable_liger_kernel: True
  tokenizer_pad_token: "<|endoftext|>" # Set pad token to eos token for Qwen2.5
  model_kwargs:
    rope_scaling:
      type: "yarn"
      factor: 4.0 # Scales 32768 * 4.0 = 131072
      original_max_position_embeddings: 32768

data:
  train:
    datasets:
      - dataset_name: "PromptResponseDataset"
        split: "train"
        dataset_kwargs:
          hf_dataset_path: "GAIR/LIMO"
          prompt_column: "question"
          response_column: "solution"
        shuffle: True
        seed: 42

training:
  trainer_type: "TRL_SFT"
  # Full fine-tuning (no PEFT)
  save_steps: 0
  num_train_epochs: 5
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2

  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  optimizer: "adamw_torch_fused"
  learning_rate: 2e-5
  warmup_ratio: 0.05
  weight_decay: 0.03
  max_grad_norm: 1e-3
  lr_scheduler_type: "cosine"
  compile: False

  dataloader_num_workers: 64 # Match LIMO preprocessing workers
  dataloader_prefetch_factor: 32

  logging_steps: 50
  log_model_summary: False
  empty_device_cache_steps: 50
  output_dir: "output/qwen2.5_7b_limo_fft_yarn"
  include_performance_metrics: True
  enable_wandb: True
  save_final_model: True

# DeepSpeed configuration for ZeRO-3 with maximum memory optimization
deepspeed:
  enable_deepspeed: True
  zero_stage: "ZERO_3"
  precision: "BF16"

  # ZeRO-3 specific parameters for memory optimization
  overlap_comm: True
  contiguous_gradients: True
  sub_group_size: 1000000000 # 1e9
  reduce_bucket_size: "auto"
  stage3_prefetch_bucket_size: "auto"
  stage3_param_persistence_threshold: "auto"
  stage3_max_live_parameters: 1000000000 # 1e9
  stage3_max_reuse_distance: 1000000000 # 1e9
  stage3_gather_16bit_weights_on_model_save: False

  # Memory optimization
  zero_allow_untested_optimizer: True
  zero_force_ds_cpu_optimizer: False

  # Optional: Enable CPU offloading for even more memory savings
  # Uncomment these lines if you need maximum memory efficiency
  # offload_optimizer:
  #   device: "cpu"
  #   pin_memory: True
  #   buffer_count: 4
  #
  # offload_param:
  #   device: "cpu"
  #   pin_memory: True
  #   buffer_count: 4

  # Logging
  steps_per_print: 10
  wall_clock_breakdown: False
