# Eval config for Qwen2 VL 2B Instruct.
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Run `pip install -U flash-attn --no-build-isolation`
#
# Usage:
#   oumi evaluate -c configs/recipes/vision/qwen2_vl_2b/evaluation/eval.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/evaluate/evaluate.html
#   - Config class: oumi.core.configs.EvaluationConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/evaluation_config.py
#   - Other eval configs: configs/**/evaluation/

model:
  model_name: "Qwen/Qwen2-VL-2B-Instruct"
  model_max_length: 1024
  torch_dtype_str: "bfloat16"
  attn_implementation: "flash_attention_2" # For this eval "sdpa" leads to CUDA OOM
  trust_remote_code: True
  shard_for_eval: True

generation:
  batch_size: 2

tasks:
  - evaluation_backend: lm_harness
    task_name: mmmu_val_computer_science
    eval_kwargs:
      num_fewshot: 5

inference_engine: NATIVE
enable_wandb: True
