# Inference config for gpt-oss-120b (MoE model with 5.1B active parameters).
#
# Usage:
#   oumi infer -i -c oumi://configs/recipes/gpt_oss/inference/120b_together_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "openai/gpt-oss-120b"

engine: TOGETHER
