# Inference config for gpt-oss-120b (MoE model with 5.1B active parameters)
# using vLLM for local inference with MXFP4 quantization.
#
# Usage:
#   oumi infer -i -c oumi://configs/recipes/gpt_oss/inference/120b_vllm_infer.yaml
#
# Requirements:
#   - Single H100 GPU (80GB) or equivalent
#   - vLLM with GPT OSS support installed
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "openai/gpt-oss-120b"
  torch_dtype_str: "bfloat16"
  trust_remote_code: true
  chat_template: "auto"  # Use model's built-in chat template

  # Enable MXFP4 quantization for efficient inference
  model_kwargs:
    quantization_config:
      quant_method: "mxfp4"

# Use vLLM engine for local inference
engine: VLLM

# Generation parameters for reasoning model
generation:
  temperature: 0.7
  max_new_tokens: 8192
  skip_special_tokens: false  # Keep reasoning tokens for GPT OSS models
