# LlamaCPP Inference config for GLM-4.5-Air GGUF (macOS compatible).
#
# Requirements:
#   - Run `pip install oumi[llama_cpp]`
#
# Usage:
#   # 1. Download the GGUF file to current working directory:
#   hf download unsloth/GLM-4.5-Air-GGUF \
#     GLM-4.5-Air-UD-Q2_K_XL.gguf --local-dir .
#
#   # 2. Run inference:
#   oumi infer -i -c configs/recipes/glm4/inference/air_gguf_macos_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "unsloth/GLM-4.5-Air-GGUF"
  tokenizer_name: "THUDM/glm-4-9b-chat"
  model_max_length: 8192
  torch_dtype_str: "float16"
  trust_remote_code: True
  model_kwargs:
    filename: "GLM-4.5-Air-UD-Q2_K_XL.gguf"

generation:
  max_new_tokens: 2048
  temperature: 0.7
  top_p: 0.9

engine: LLAMACPP
