# OpenAI Inference config for GPT-4.1-mini.
#
# Requirements:
#   - Set environment variable: export OPENAI_API_KEY=your_key_here
#
# Usage:
#   oumi infer -i -c configs/apis/openai/infer_gpt_4_1_mini.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "gpt-4.1-mini"

engine: OPENAI

generation:
  max_new_tokens: 16384
  temperature: 1.0
