# GPT2 inference config.
#
# Usage:
#   oumi infer -i -c configs/recipes/gpt2/inference/infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/

model:
  model_name: "openai-community/gpt2"
  chat_template: "gpt2"
  tokenizer_pad_token: "<|endoftext|>"
  trust_remote_code: True

generation:
  max_new_tokens: 32
  batch_size: 1

engine: NATIVE
