# GPT2 pretraining GCP job config.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi launch up -c configs/recipes/gpt2/pretraining/gcp_job.yaml --cluster gpt-pt
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml

name: gpt2-pt

resources:
  cloud: gcp
  accelerators: "A100-80GB"
  use_spot: false

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: gpt2.pt

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu]

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c configs/recipes/gpt2/pretraining/train.yaml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
      --training.max_steps 100 \
      --training.ddp_find_unused_parameters false \
      --training.dataloader_num_workers 2 \
      --training.dataloader_prefetch_factor 4 \
      --training.enable_wandb true

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
