# Phi4 multimodal 5.6B full fine-tune training job config.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#
# Usage:
#   oumi launch up --config configs/recipes/vision/phi4/sft/full/gcp_job.yaml --cluster phi4-multimodal
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml

name: phi4-mm-sft-oumi-train

resources:
  cloud: gcp
  accelerators: "A100:1"
  use_spot: false
  disk_size: 1000 # Disk size in GBs

num_nodes: 1 # Set it to N for multi-node training.

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials
  ~/.cache/huggingface/token: ~/.cache/huggingface/token # HF credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: phi4-vl.fft

setup: |
  set -e

  pip install uv && uv pip install oumi[gpu] hf_transfer
  # Install model from HF Hub. This tool increases download speed compared to
  # downloading the model during training.
  HF_HUB_ENABLE_HF_TRANSFER=1 hf download microsoft/Phi-4-multimodal-instruct

  # The model requires flash_attention_2! Install it here.
  pip install -U flash-attn --no-build-isolation

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh
  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c configs/recipes/vision/phi4/sft/full/train.yaml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
      --training.max_steps 25 \
      --training.save_steps 0 \
      --training.save_final_model false

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
