model:
  model_name: "meta/llama-3.3-70b-instruct-maas"

inference_engine: GOOGLE_VERTEX

generation:
  max_new_tokens: 8192
  temperature: 0.0

tasks:
  - evaluation_backend: custom
    task_name: berry_bench
